# █   █ █▀▀█ █▀▀█ █▀▀█ █▀▀ Made by Nescaaallz.
# █ █ █ █▄▄█ █▄▄▀ █▀▀▀ ▀▀█ If you have problems with this system contact me.
# █▄▀▄█ ▀  ▀ ▀  ▀ █    ▀▀▀ My discord is Nescaaallz#5060.

Messages:
  Warp:
    Usage:
    - "&cCorrect usage: /warp <warp>"
    OnlyPlayers:
    - "&4Only players can perform this command."
    Denied:
    - "&cYou are not authorized to go to this warp."
    Teleported:
    - "&eTeleported to warp '%warp%'."
    Undefined:
    - "&eWarp '%warp%' don't exists."
  Warps:
    OnlyPlayers:
    - "&4Only players can perform this command."
    Title:
    - "&e&lServer warps"
    # SendInteractiveMessage - Send message with click & hover event.
    SendInteractiveMessage: true
    # Hover - Part of InteractiveMessage. (shows in hover event)
    Hover:
    - " "
    - "&5Click to teleport to &l%warp&5."
    Separator:
    - "&e, "
    WarpColor:
    - "&6"
    NoResults:
    - "&cNo warp found."
  Setwarp:
    Usage:
    - "&cCorrect usage: /setwarp <warp>"
    OnlyPlayers:
    - "&4Only players can perform this command."
    Denied:
    - "&cYou are not authorized to perform this command."
    RemovedWarp:
    - "&eWarp '%warp%' defined successfully."
  Delwarp:
    Usage:
    - "&cCorrect usage: /delwarp <warp>"
    OnlyPlayers:
    - "&4Only players can perform this command."
    Denied:
    - "&cYou are not authorized to perform this command."
    RemovedWarp:
    - "&eWarp '%warp%' removed successfully."
    Undefined:
    - "&eWarp '%warp%' don't exists."

Warps: {}